export const songObject = {
	added_at: '2020-05-13T14:32:07Z',
	added_by: {
		external_urls: {
			spotify: 'https://open.spotify.com/user/31g4sq5a5bu5oonkugoczlg3pfqm',
		},
		href: 'https://api.spotify.com/v1/users/31g4sq5a5bu5oonkugoczlg3pfqm',
		id: '31g4sq5a5bu5oonkugoczlg3pfqm',
		type: 'user',
		uri: 'spotify:user:31g4sq5a5bu5oonkugoczlg3pfqm',
	},
	is_local: false,
	primary_color: null,
	track: {
		album: {
			album_type: 'album',
			artists: [
				{
					external_urls: {
						spotify: 'https://open.spotify.com/artist/554yyXUEFseU1dwvisHTik',
					},
					href: 'https://api.spotify.com/v1/artists/554yyXUEFseU1dwvisHTik',
					id: '554yyXUEFseU1dwvisHTik',
					name: 'Monty Sharma',
					type: 'artist',
					uri: 'spotify:artist:554yyXUEFseU1dwvisHTik',
				},
				{
					external_urls: {
						spotify: 'https://open.spotify.com/artist/5eWpthiGD66CLD4bQjvIBp',
					},
					href: 'https://api.spotify.com/v1/artists/5eWpthiGD66CLD4bQjvIBp',
					id: '5eWpthiGD66CLD4bQjvIBp',
					name: 'Sanjay Leela Bhansali',
					type: 'artist',
					uri: 'spotify:artist:5eWpthiGD66CLD4bQjvIBp',
				},
			],
			available_markets: [
				'AR',
				'AU',
				'AT',
				'BE',
				'BO',
				'BR',
				'BG',
				'CA',
				'CL',
				'CO',
				'CR',
				'CY',
				'CZ',
				'DK',
				'DO',
				'DE',
				'EC',
				'EE',
				'SV',
				'FI',
				'FR',
				'GR',
				'GT',
				'HN',
				'HK',
				'HU',
				'IS',
				'IE',
				'IT',
				'LV',
				'LT',
				'LU',
				'MY',
				'MT',
				'NL',
				'NZ',
				'NI',
				'NO',
				'PA',
				'PY',
				'PE',
				'PH',
				'PL',
				'PT',
				'SG',
				'SK',
				'ES',
				'SE',
				'CH',
				'TW',
				'TR',
				'UY',
				'US',
				'GB',
				'AD',
				'LI',
				'MC',
				'ID',
				'JP',
				'TH',
				'VN',
				'RO',
				'IL',
				'ZA',
				'SA',
				'AE',
				'BH',
				'QA',
				'OM',
				'KW',
				'EG',
				'MA',
				'DZ',
				'TN',
				'LB',
				'JO',
				'PS',
				'IN',
				'BY',
				'KZ',
				'MD',
				'UA',
				'AL',
				'BA',
				'HR',
				'ME',
				'MK',
				'RS',
				'SI',
				'KR',
				'BD',
				'PK',
				'LK',
				'GH',
				'KE',
				'NG',
				'TZ',
				'UG',
				'AG',
				'AM',
				'BS',
				'BB',
				'BZ',
				'BT',
				'BW',
				'BF',
				'CV',
				'CW',
				'DM',
				'FJ',
				'GM',
				'GE',
				'GD',
				'GW',
				'GY',
				'HT',
				'JM',
				'KI',
				'LS',
				'LR',
				'MW',
				'MV',
				'ML',
				'MH',
				'FM',
				'NA',
				'NR',
				'NE',
				'PW',
				'PG',
				'WS',
				'SM',
				'ST',
				'SN',
				'SC',
				'SL',
				'SB',
				'KN',
				'LC',
				'VC',
				'SR',
				'TL',
				'TO',
				'TT',
				'TV',
				'VU',
				'AZ',
				'BN',
				'BI',
				'KH',
				'CM',
				'TD',
				'KM',
				'GQ',
				'SZ',
				'GA',
				'GN',
				'KG',
				'LA',
				'MO',
				'MR',
				'MN',
				'NP',
				'RW',
				'TG',
				'UZ',
				'ZW',
				'BJ',
				'MG',
				'MU',
				'MZ',
				'AO',
				'CI',
				'DJ',
				'ZM',
				'CD',
				'CG',
				'IQ',
				'LY',
				'TJ',
				'VE',
				'ET',
				'XK',
			],
			external_urls: {
				spotify: 'https://open.spotify.com/album/4E6rpd9IcOfe6X8mErzVxf',
			},
			href: 'https://api.spotify.com/v1/albums/4E6rpd9IcOfe6X8mErzVxf',
			id: '4E6rpd9IcOfe6X8mErzVxf',
			images: [
				{
					height: 640,
					url: 'https://i.scdn.co/image/ab67616d0000b273bd848c36d02a36a7610d9641',
					width: 640,
				},
				{
					height: 300,
					url: 'https://i.scdn.co/image/ab67616d00001e02bd848c36d02a36a7610d9641',
					width: 300,
				},
				{
					height: 64,
					url: 'https://i.scdn.co/image/ab67616d00004851bd848c36d02a36a7610d9641',
					width: 64,
				},
			],
			name: 'Saawariya (Original Motion Picture Soundtrack)',
			release_date: '2007-09-14',
			release_date_precision: 'day',
			total_tracks: 11,
			type: 'album',
			uri: 'spotify:album:4E6rpd9IcOfe6X8mErzVxf',
		},
		artists: [
			{
				external_urls: {
					spotify: 'https://open.spotify.com/artist/554yyXUEFseU1dwvisHTik',
				},
				href: 'https://api.spotify.com/v1/artists/554yyXUEFseU1dwvisHTik',
				id: '554yyXUEFseU1dwvisHTik',
				name: 'Monty Sharma',
				type: 'artist',
				uri: 'spotify:artist:554yyXUEFseU1dwvisHTik',
			},
			{
				external_urls: {
					spotify: 'https://open.spotify.com/artist/5cB4d4jPYjMT326sjihQ4m',
				},
				href: 'https://api.spotify.com/v1/artists/5cB4d4jPYjMT326sjihQ4m',
				id: '5cB4d4jPYjMT326sjihQ4m',
				name: 'Shaan',
				type: 'artist',
				uri: 'spotify:artist:5cB4d4jPYjMT326sjihQ4m',
			},
		],
		available_markets: [
			'AR',
			'AU',
			'AT',
			'BE',
			'BO',
			'BR',
			'BG',
			'CA',
			'CL',
			'CO',
			'CR',
			'CY',
			'CZ',
			'DK',
			'DO',
			'DE',
			'EC',
			'EE',
			'SV',
			'FI',
			'FR',
			'GR',
			'GT',
			'HN',
			'HK',
			'HU',
			'IS',
			'IE',
			'IT',
			'LV',
			'LT',
			'LU',
			'MY',
			'MT',
			'NL',
			'NZ',
			'NI',
			'NO',
			'PA',
			'PY',
			'PE',
			'PH',
			'PL',
			'PT',
			'SG',
			'SK',
			'ES',
			'SE',
			'CH',
			'TW',
			'TR',
			'UY',
			'US',
			'GB',
			'AD',
			'LI',
			'MC',
			'ID',
			'JP',
			'TH',
			'VN',
			'RO',
			'IL',
			'ZA',
			'SA',
			'AE',
			'BH',
			'QA',
			'OM',
			'KW',
			'EG',
			'MA',
			'DZ',
			'TN',
			'LB',
			'JO',
			'PS',
			'IN',
			'BY',
			'KZ',
			'MD',
			'UA',
			'AL',
			'BA',
			'HR',
			'ME',
			'MK',
			'RS',
			'SI',
			'KR',
			'BD',
			'PK',
			'LK',
			'GH',
			'KE',
			'NG',
			'TZ',
			'UG',
			'AG',
			'AM',
			'BS',
			'BB',
			'BZ',
			'BT',
			'BW',
			'BF',
			'CV',
			'CW',
			'DM',
			'FJ',
			'GM',
			'GE',
			'GD',
			'GW',
			'GY',
			'HT',
			'JM',
			'KI',
			'LS',
			'LR',
			'MW',
			'MV',
			'ML',
			'MH',
			'FM',
			'NA',
			'NR',
			'NE',
			'PW',
			'PG',
			'WS',
			'SM',
			'ST',
			'SN',
			'SC',
			'SL',
			'SB',
			'KN',
			'LC',
			'VC',
			'SR',
			'TL',
			'TO',
			'TT',
			'TV',
			'VU',
			'AZ',
			'BN',
			'BI',
			'KH',
			'CM',
			'TD',
			'KM',
			'GQ',
			'SZ',
			'GA',
			'GN',
			'KG',
			'LA',
			'MO',
			'MR',
			'MN',
			'NP',
			'RW',
			'TG',
			'UZ',
			'ZW',
			'BJ',
			'MG',
			'MU',
			'MZ',
			'AO',
			'CI',
			'DJ',
			'ZM',
			'CD',
			'CG',
			'IQ',
			'LY',
			'TJ',
			'VE',
			'ET',
			'XK',
		],
		disc_number: 1,
		duration_ms: 284573,
		episode: false,
		explicit: false,
		external_ids: {
			isrc: 'INS170709290',
		},
		external_urls: {
			spotify: 'https://open.spotify.com/track/0gRNu9dVzi5aC87AI1empZ',
		},
		href: 'https://api.spotify.com/v1/tracks/0gRNu9dVzi5aC87AI1empZ',
		id: '0gRNu9dVzi5aC87AI1empZ',
		is_local: false,
		name: 'Jab Se Tere Naina',
		popularity: 71,
		preview_url:
			'https://p.scdn.co/mp3-preview/a09d80651883f9e2a46852a07902d3645e508bf6?cid=c111d8cd377f4cf0946e51bf5470f005',
		track: true,
		track_number: 2,
		type: 'track',
		uri: 'spotify:track:0gRNu9dVzi5aC87AI1empZ',
	},
	video_thumbnail: {
		url: null,
	},
};
